// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdRZ9a09bkDR4nXOlfvpub4RAKEp1PJas',
    appId: '1:472886407937:web:708a59947c0302b6a1a100',
    messagingSenderId: '472886407937',
    projectId: 'qauntum-assignment',
    authDomain: 'qauntum-assignment.firebaseapp.com',
    storageBucket: 'qauntum-assignment.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhQUlgqzARni2VOqs4X8L3jg3Es38ywi8',
    appId: '1:472886407937:android:da7f5425e89e811da1a100',
    messagingSenderId: '472886407937',
    projectId: 'qauntum-assignment',
    storageBucket: 'qauntum-assignment.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB32xMGb0W_uDefibdk_Im0Kh0X-wPYi94',
    appId: '1:472886407937:ios:a07cbf4bdf14c356a1a100',
    messagingSenderId: '472886407937',
    projectId: 'qauntum-assignment',
    storageBucket: 'qauntum-assignment.appspot.com',
    iosClientId: '472886407937-pse6cfraerpjgas9f246u006krmpmfv8.apps.googleusercontent.com',
    iosBundleId: 'com.example.quantumAssignment',
  );
}
